#!/bin/sh
#
DIR=$1 ; if [ -z "$DIR" ]; then DIR=../man; fi
#
for f in ${DIR}/*
do 
    # SunOS 4:  grep -s : 'silent', only "error status"
    if grep -s '^EXAMPLES(' > /dev/null $f 
    then i=0 # Whoah, horrible code.... need a dummy statement rather use if NOT
    else echo $f | sed "s#${DIR}/##"
    fi
done
