#! /bin/sh
#---- Create the 'dvi' file of the function help ---- needs LATEX ! --
DVIDIR=../../../../dvi
   D2L=../../../../etc/doc2latex

# Should work WHEREVER this is called from :
cd `dirname $0`/..
cp mansrc/latex/Man.tex dvi
cp mansrc/latex/Rdoc.sty dvi
cd src/library/base/man

$D2L `ls -A | sort -f| sed '/CVS/d;/~$/d;/\.bak$/d;/\.orig$/d'` > ${DVIDIR}/doc.tex
(cd $DVIDIR;
 latex Man
 if [ -x `which xdvi` ];then xdvi Man & 
 fi
)
