#!/bin/sh

RHOME=`pwd`; export RHOME
LIBS=`ls src/library | sed '
/Makefile/d
/CVS/d
/LIB*/d
/base/d
/profile/d'`

cp /dev/null help/LibIndex

for lib in $LIBS
do
	echo "Manual entries for $lib"
	if [ ! -d help/$lib ]
	then
		mkdir help/$lib
	fi

	cp /dev/null help/$lib/AnIndex

	FILES="`ls src/library/$lib/man | sed /CVS/d`"
	for file in $FILES
	do
		./etc/doc2ms src/library/$lib/man/$file | nroff -ms 2> /dev/null | ./etc/help.pretty | sed 's/^/	/' >  help/$lib/$file
		echo $file
	done

	(
	for file in $FILES
	do
		NAMES=`grep 'ALIAS([A-Za-z.]' src/library/$lib/man/$file | sed '
		s/ALIAS(\(.*\))$/\1/'`
		for name in $NAMES
		do
			echo "$name	$file"
		done
	done
	for file in $FILES
	do
		echo "$file	$file"
	done
	) | sort -d -f >> help/$lib/AnIndex

	if [ -f src/library/$lib/TITLE ]
	then
		cat src/library/$lib/TITLE >> help/LibIndex
		cp src/library/$lib/TITLE help/$lib/TITLE
	fi

	if [ -f src/library/$lib/INDEX ]
	then
		cp src/library/$lib/INDEX help/$lib/INDEX
	fi

done
