#!/bin/sh

HTMLDIR=../../../../html
Index=$HTMLDIR/funs/index.html
D2H=../../../../etc/doc2html

# Should work WHEREVER this is called from :
cd `dirname $0`/../src/library/base/man

for i in `ls -A | sed '/CVS/d; /~$/d; /.bak$/d'`
do
	$D2H $i > $HTMLDIR/funs/$i.html
	echo $i
done

cat > $Index << 'END'
<HEAD><TITLE>R Function Index</TITLE></HEAD>
<BODY LINK=#0000EF VLINK=#0000EF>
<HR ALIGN=middle>
<H2><CENTER><I>R Function Index<I></CENTER></H2>
<HR ALIGN=middle>
END

grep TITLE `ls -Ad * | sed /CVS/d` | sed '
s!^\(.*\)TITLE(!\1@!
s!)$!!
s! @@ !@!
s!:!!
' | sort -t@ -d -f +0 | awk -F@ '
BEGIN {k=0 ; printf("<CENTER><TABLE>\n") ; printf("<TR ALIGN=LEFT>\n")}
{ printf("<TD WIDTH=20%%><A HREF=\"%s.html\">%s</A>\n",$2,$1)
k=k+1 ; if(k == 5) { printf("<TR ALIGN=LEFT>\n"); k=0 }}
END { printf("</TABLE></CENTER>\n") }
' >> $Index
echo '</BODY>' >> $Index
